### PR TITLE
Fix Issue #18

### PR DESCRIPTION
**Pull request by FlyingGraysons**

### CODE REVIEW

**Comment by truell20** [comment]
@FlyingGraysons Thats a hacky way of doing it. hiddenActivationFunctionDerivative and outputActivationFunctionDerivative should be taken out, because they dont need to be members. the load function should be private.

**Comment by FlyingGraysons** [comment]
It is private @truell20

**Comment by truell20** [comment]
Why the clean option?

**Comment by truell20** [comment]
@FlyingGraysons

**Comment by truell20** [comment]
Also change the title.

**Pull request closed without merging**
