### PR TITLE
Added better example code

### PR DESCRIPTION
**Pull request by FlyingGraysons**

### CODE REVIEW

**Comment by truell20** [comment]
What did you do to our indent @FlyingGraysons

**Comment by truell20** [comment]
We use spaces not tabs.

**Comment by joshuagruenstein** [comment]
I'm not such a fan of the printing functionality.  Many of the platforms we're targeting don't support console output, and we're trying to reduce standard library reliance, not increase it.

**Comment by truell20** [comment]
@joshuagruenstein What printing functionality? We already had a method for printing neuron weights. @FlyingGraysons Did not add that

**Comment by truell20** [comment]
@FlyingGraysons @joshuagruenstein I am fine with the example code changes. Changes to indents of other files will be taken out, as I have moved us to tabs.

**Comment by truell20** [comment]
@FlyingGraysons revert the changes to the other files and ill merge

**Pull request closed without merging**
