### PR TITLE
Style corrections

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick J.P <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by truell20** [comment]
@patrickelectric Did you just change the indentation from 2 spaces to 4 spaces?

**Comment by patrickelectric** [comment]
@truell20 From 4 to 2 spaces.

**Comment by truell20** [comment]
@patrickelectric git says that there are 8,718 additions and 8,501 deletions. What is the 217 additions that are not coupled with a deletion? Is it not that when just changing indentation, each addition should be coupled with a deletion?

**Comment by truell20** [comment]
@patrickelectric  Also pretty sure that you didn't do it correctly. Seems that you are deleting two spaces from every indented line, when to go from 4 to 2, you would have to delete 2 spaces for every indentation level.

**Comment by truell20** [comment]
@patrickelectric We already use 2 spaces per indentation level.

**Comment by patrickelectric** [comment]
@truell20, take a look in catch.h
(original)[https://github.com/FidoProject/Fido/blob/master/tests/catch.h] and (changed)[https://github.com/patrickelectric/Fido/blob/d7da5ef21ce123b13f440fadbb7d401005235410/tests/catch.h]. The original don't have identatation, that's why it have 217 additions.

Some namespaces have indentation..., take a look (here)[http://llvm.org/docs/CodingStandards.html#namespace-indentation], (here)[http://seanmiddleditch.com/unnest-c-namespaces/] and (here)[https://webkit.org/code-style-guidelines/] about this.

Some files use allman style, take a look (here)[https://github.com/FidoProject/Fido/pull/60/commits/d7da5ef21ce123b13f440fadbb7d401005235410#diff-a4af4ee8941b0b334e628d001fdb5cddL230].

Some don't have space before brackets, (here)[https://github.com/FidoProject/Fido/pull/60/commits/d7da5ef21ce123b13f440fadbb7d401005235410#diff-8894632c570d670eb46cce2124660e4dR7].

**Comment by truell20** [comment]
@patrickelectric Thank you for the detailed description.

**Comment by truell20** [comment]
We hadn't touched the catch.h source since it is a third-party testing library

**Comment by patrickelectric** [comment]
Style correction without catch.h (third-paty).

**Comment by truell20** [comment]
@patrickelectric Thank you

**Pull request merged**
