### PR TITLE
Add better example and library support

### PR DESCRIPTION
**Pull request by FlyingGraysons**

### CODE REVIEW

**Comment by FlyingGraysons** [comment]
Will add library support at least on unix based systems

**Comment by FlyingGraysons** [comment]
Fixes #8

**Comment by truell20** [comment]
@FlyingGraysons can you test on Windows soon?

**Comment by truell20** [comment]
Also, @FlyingGraysons fix the duplicate comments in your README.

**Comment by FlyingGraysons** [comment]
How about now @truell20

**Comment by truell20** [comment]
@FlyingGraysons Nope. You have a duplicate backprop object in the README.

**Pull request merged**
